menu title Select the boot mode
timeout 5
default imx6ull-atk-ext4fs
label imx6ull-atk-ext4fs
  kernel /zImage
  devicetree /imx6ull-14x14-atk.dtb
  append root=/dev/mmcblk1p2 rootwait console=ttySTM0,115200

label imx6ull-atk-ramdisk
  kernel /zImage
  devicetree /imx6ull-14x14-atk.dtb
  initrd /rootfs.cpio.gz
  append root=/dev/ram0 rootwait console=ttySTM0,115200
