#!/bin/sh

# emmc partitions:
# Device       Boot StartCHS    EndCHS        StartLBA     EndLBA    Sectors  Size Id Type
# /dev/mmcblk1p1 *  1,70,6      17,151,6         20480     282623     262144  128M  c Win95 FAT32 (LBA)
# /dev/mmcblk1p2    17,151,7    50,58,8         282624     806911     524288  256M 83 Linux

ERR=true
NOTICE=true

err() {
	if [ "$ERR" ]; then
		echo "$0": "$*" >&2
	fi
}

notice() {
	if [ "$NOTICE" ]; then
		echo "$0": "$*" >&1
	fi
}

# check cmd executed success
execute ()
{
    $* >/dev/null
    if [ $? -ne 0 ]; then
        echo
        echo "failed: execute $*"
        echo
        exit 1
    fi
}

# sdcard block device
sdcard_device="/dev/mmcblk0"
# emmc block device
emmc_device="/dev/mmcblk1"

# uboot
uboot="u-boot.imx"
# kernel
kernel="zImage"

# check whether the selected block device exists and is not sdcard partitions
is_not_sdcard() {
	cat /proc/cmdline | grep " root=${sdcard_device}" > /dev/null
}

# umount emmc partitions
umount_partitions() {
	for i in $(ls -1 ${emmc_device}p?); do
 		echo "umount device '$i'"
 		umount $i 2>/dev/null
	done
}

# create emmc partitions
create_emmc_partitions() {

	# umount before partitioning
	umount_partitions

	# clean up any existing partition data
	execute "dd if=/dev/zero of=${emmc_device} bs=1024 count=1024"

# create MBR partitions
# bootfs(partition number) bootable flag
cat << END | fdisk -H 255 -S 63 ${emmc_device}
n
p
1
20480
+128M
n
p
2
282624
+256M
t
1
c
a
1
w
END

	sleep 3
	# system will automatically mount after the partition created, 
	# so umount it here again
	umount_partitions

	# format emmc partition
	notice "Format emmc partition"
	# partition 1 is formatted in Fat32
	mkfs.vfat -F 32 -n "bootfs" ${emmc_device}p1 >/dev/null 2>&1
	# partition 2 is formatted in ext4
	mkfs.ext4 -F -L "rootfs" ${emmc_device}p2 >/dev/null 2>&1

	return 0
}

# sdcard deploy image to emmc
sdcard_deploy_image_to_emmc() {
	# mount sdcard bootfs partitions
	if ! mount -o rw ${sdcard_device}p1 /media; then
		return 1
	fi
	
	# write uboot
	# Before writing, enable mmcblk1boot0
	echo 0 > /sys/block/mmcblk1boot0/force_ro
	execute "dd if=/media/${uboot} of=${emmc_device}boot0 bs=1024 seek=1 conv=fsync"
	echo 1 >/sys/block/mmcblk1boot0/force_ro

	# write dtb and kernel
	execute "dd if=${sdcard_device}p1 of=${emmc_device}p1"
	sync

	# write filesystem
	execute "dd if=${sdcard_device}p2 of=${emmc_device}p2"
	sync

	# umount partitions
	umount /media

	return 0
}

# deploy image to emmc
notice "Start deploy image to emmc"
if ! is_not_sdcard; then
	notice "Operation may be system partition,skip..."
	exit 1
fi

notice "Create emmc partition"
if ! create_emmc_partitions; then
	err "Create emmc partition error !"
	exit 1
fi
notice "Deploy image to emmc"
if ! sdcard_deploy_image_to_emmc; then
	err "Deploy image to emmc error !"
	exit 1
fi
notice "Successful deploy image to emmc !"
